name: deploy-anvil-support-dev

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch:
    inputs:
      apply:
        description: Run Terraform Apply
        description: "Run Terraform apply"
        type: choice
        required: false
        default: false
        options:
          - false
          - true

env:
  application: anvil-support
  environment: dev

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/terraform.yaml
    with:
      application: anvil-support
      apply: ${{ github.event_name == 'pull_request' && false || inputs.apply || true }}
      aws_region: us-west-2
      environment: dev
    secrets: inherit
