name: build-anvil-support-dev

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - Dockerfile

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      application: anvil-support
      aws_region: us-west-2
      environment: dev
      push: ${{ github.event_name != 'pull_request' && true || false }}
    secrets: inherit
