name: release-anvil-support-dev

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - Dockerfile

jobs:
  release:
    name: release
    uses: ./.github/workflows/release.yaml
    secrets: inherit
