name: Terraform

on:
  workflow_call:
    inputs:
      application:
        description: "Application Name"
        type: string
        required: true
      apply:
        description: "Run Terraform apply"
        type: boolean
        required: false
        default: false
      aws_region:
        description: "AWS Region"
        type: string
        required: false
        default: us-west-2
      environment:
        description: "Application Environment"
        type: string
        required: true

env:
  backend_config: "tfvars/${{inputs.application}}-${{inputs.environment}}-backend.tfvars"
  tf_config: "tfvars/${{inputs.application}}-${{inputs.environment}}.tfvars"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{inputs.aws_region}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -backend-config=${{env.backend_config}}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -no-color -var-file=${{env.tf_config}}

      - name: Terraform Apply
        if: "${{ inputs.apply == 'true' }}"
        run: terraform apply -auto-approve -no-color -var-file=${{env.tf_config}}
